name: GraalVM -Pagent tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  graalvm-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        graalvm_java:
          - '21'
          - '24'
          - '25'
          - '25.0.0'

    name: Node (GraalVM Java ${{ matrix.graalvm_java }})

    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM (Java ${{ matrix.graalvm_java }})
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: ${{ matrix.graalvm_java }}
          native-image-musl: true
          cache: gradle

      - name: Show Java / GraalVM version
        run: |
          java -version
          native-image --version

      - name: Extract major Java version
        id: java_version
        run: |
          v='${{ matrix.graalvm_java }}'
          echo "short=${v%%.*}" >> "$GITHUB_OUTPUT"

      - run: ./gradlew test -Pagent -PjavaVersion=${{ steps.java_version.outputs.short }} --no-daemon --stacktrace --info

      - uses: actions/upload-artifact@v5
        with:
          name: native-image-metadata-graalvm-${{ matrix.graalvm_java }}
          path: build/native/agent-output/test
